spring.application.name=pocmwigw
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.name=pocmwigw,routing
spring.profiles.active=local
management.endpoints.web.exposure.include=health,refresh